defaults: &defaults
  show_drugs_with_price_only: false
  maps:
    default_lat_lon: [55.753994, 37.622093]
    zoom: 8

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
